package router

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"
)

// TestHealthEndpoint verifies the /health liveness probe returns 200.
func TestHealthEndpoint(t *testing.T) {
	h := &Handlers{}
	r := Setup("test", h, nil, "")

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/health", nil)
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("expected status 200, got %d", w.Code)
	}

	var body map[string]interface{}
	if err := json.Unmarshal(w.Body.Bytes(), &body); err != nil {
		t.Fatalf("failed to parse response body: %v", err)
	}

	if body["status"] != "ok" {
		t.Errorf("expected status 'ok', got %v", body["status"])
	}

	// Trace ID should be present (auto-generated by middleware)
	if _, exists := body["trace_id"]; !exists {
		t.Error("expected trace_id in response")
	}
}

// TestHealthEndpointWithTraceID verifies that a client-provided X-Trace-ID is echoed back.
func TestHealthEndpointWithTraceID(t *testing.T) {
	h := &Handlers{}
	r := Setup("test", h, nil, "")

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/health", nil)
	req.Header.Set("X-Trace-ID", "test-trace-123")
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("expected status 200, got %d", w.Code)
	}

	// Response header should echo the trace ID
	if got := w.Header().Get("X-Trace-ID"); got != "test-trace-123" {
		t.Errorf("expected X-Trace-ID 'test-trace-123', got %q", got)
	}
}

// TestReadyEndpointNoDeps verifies /ready returns 200 when no dependencies are provided.
func TestReadyEndpointNoDeps(t *testing.T) {
	h := &Handlers{}
	r := Setup("test", h, nil, "")

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/ready", nil)
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("expected status 200, got %d", w.Code)
	}

	var body map[string]interface{}
	if err := json.Unmarshal(w.Body.Bytes(), &body); err != nil {
		t.Fatalf("failed to parse response body: %v", err)
	}

	if body["status"] != "ready" {
		t.Errorf("expected status 'ready', got %v", body["status"])
	}
}

// TestCORSHeaders verifies that CORS headers are set correctly.
func TestCORSHeaders(t *testing.T) {
	h := &Handlers{}
	r := Setup("test", h, []string{"http://localhost:3000"}, "")

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/health", nil)
	req.Header.Set("Origin", "http://localhost:3000")
	r.ServeHTTP(w, req)

	if got := w.Header().Get("Access-Control-Allow-Origin"); got != "http://localhost:3000" {
		t.Errorf("expected CORS origin 'http://localhost:3000', got %q", got)
	}
}

// TestCORSRejectsUnknownOrigin verifies that unknown origins don't get CORS headers.
func TestCORSRejectsUnknownOrigin(t *testing.T) {
	h := &Handlers{}
	r := Setup("test", h, []string{"http://localhost:3000"}, "")

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/health", nil)
	req.Header.Set("Origin", "http://evil.example.com")
	r.ServeHTTP(w, req)

	if got := w.Header().Get("Access-Control-Allow-Origin"); got != "" {
		t.Errorf("expected no CORS origin for unknown origin, got %q", got)
	}
}

// TestCORSPreflightOptions verifies OPTIONS requests return 204.
func TestCORSPreflightOptions(t *testing.T) {
	h := &Handlers{}
	r := Setup("test", h, []string{"http://localhost:3000"}, "")

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("OPTIONS", "/api/v1/sessions", nil)
	req.Header.Set("Origin", "http://localhost:3000")
	r.ServeHTTP(w, req)

	if w.Code != http.StatusNoContent {
		t.Errorf("expected status 204 for preflight, got %d", w.Code)
	}
}

// TestSwaggerEndpointRegistered verifies that the Swagger route is registered.
// Note: actual Swagger content requires docs to be loaded via main.go init.
func TestSwaggerEndpointRegistered(t *testing.T) {
	h := &Handlers{}
	r := Setup("test", h, nil, "")

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/swagger/index.html", nil)
	r.ServeHTTP(w, req)

	// Swagger route exists but may 404 without docs init.
	// The key assertion: it's not a 405 (method not allowed) which would mean no route.
	if w.Code == http.StatusMethodNotAllowed {
		t.Error("swagger route should be registered")
	}
}

// TestMetricsEndpoint verifies that Prometheus metrics are served.
func TestMetricsEndpoint(t *testing.T) {
	h := &Handlers{}
	r := Setup("test", h, nil, "")

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/metrics", nil)
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("expected status 200 for metrics, got %d", w.Code)
	}

	// Metrics response should contain prometheus format
	body := w.Body.String()
	if len(body) == 0 {
		t.Error("expected non-empty metrics response")
	}
}

// TestAdminEndpointRequiresToken verifies that admin routes need authentication.
func TestAdminEndpointRequiresToken(t *testing.T) {
	h := &Handlers{}
	r := Setup("test", h, nil, "secret-admin-token")

	// Without token
	w := httptest.NewRecorder()
	req, _ := http.NewRequest("POST", "/api/v1/admin/fund-pool/seed", nil)
	r.ServeHTTP(w, req)

	if w.Code != http.StatusUnauthorized {
		t.Errorf("expected 401 without token, got %d", w.Code)
	}

	// With wrong token
	w = httptest.NewRecorder()
	req, _ = http.NewRequest("POST", "/api/v1/admin/fund-pool/seed", nil)
	req.Header.Set("X-Admin-Token", "wrong-token")
	r.ServeHTTP(w, req)

	if w.Code != http.StatusUnauthorized {
		t.Errorf("expected 401 with wrong token, got %d", w.Code)
	}
}

// TestAdminDisabledWhenNoToken verifies admin access is forbidden when token is empty.
func TestAdminDisabledWhenNoToken(t *testing.T) {
	h := &Handlers{}
	r := Setup("test", h, nil, "")

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("POST", "/api/v1/admin/fund-pool/seed", nil)
	r.ServeHTTP(w, req)

	if w.Code != http.StatusForbidden {
		t.Errorf("expected 403 when admin token not configured, got %d", w.Code)
	}
}
